### PR TITLE
[Ready] We'll just sync everything because holy shit memes.

### LINKED ISSUE #6043: Chaplain bible ignores cryosleep
**Round ID**: 12174

**Desc**: As it says on the tin; a Chaplain Cryo'd and the one that joined after him had the previous player's bible instead of his own inside of his backpack. Does not effect Null Rod.

**How to reproduce**: Join round as Chaplain. Cryo. Chaplain slot is opened. New Chaplain joins. Instead of his respective bible, he gets your bible.

### LINKED ISSUE #6255: Heirloom items not making it to the station with their owners.
Issue reported from  Round ID: 12349 (Citadel Station 13)
Late joined. 
"There is a precious family staff of storms at your feet, passed down from generation to generation. Keep it safe!"

Granted, this may be entirely tied to april fools shenanigans, but  a bug nonetheless. May be tied to characters initially appearing at the lobby screen and the item never making the transition over to the station.

### LINKED ISSUE #6278: Box Station Engineering has no Wardrobe Locker
Due to removing of the Supermatter Engine, the locker for jumpsuits and backpacks is gone.

### LINKED ISSUE #6298: Tesla cams not linked to monitors or station cams
Issue reported from  Round ID: 12391 (Citadel Station 13)

Reporting client version: 512

Tesla cams on both Box and Meta station are not linked to the cams inside of the tesla field, in fact there is no cams even linked to them making them pointless.
Locations
https://cdn.discordapp.com/attachments/397095957373648897/432005659639152642/Broken_cam_one.png
https://cdn.discordapp.com/attachments/397095957373648897/432005669516869632/Broken_cam_two.png
No Photo: Last place is Meta station sec room were its a "Engine monitor" yet has no cam links to them to see inside containment

[Reproduction]: # Click on any of the "Engine monitors" and have no cams linked to them

### LINKED ISSUE #6402: labeling pill bottles creates label twice
What the title says.
Trying to label pill bottles creates the label twice.

> 
> Zander Sylphaen labels the pill bottle as Mutadone.
> Zander Sylphaen labels the pill bottle (Mutadone) as Mutadone.

### LINKED ISSUE #6628: Flashes sprite missing/invisible
Issue reported from  Round ID: 12708 (Citadel Station 13)

Reporting client version: 512

Flashes had no sprite or were totally invisible. Was able to click the item slot to equip/pick them up, but other than that they were invisible.

### LINKED ISSUE #6647: Transfer Pipes Invisible/Unusable
Issue reported from  Round ID: 12735 (Citadel Station 13)

Reporting client version: 512

Transfer pipe sprite missing?
tank transfer valve

[Reproduction]: Merely going to RnD?

### LINKED ISSUE #6648: Create Hypovials in the Chemmaster is broken.
https://i.imgur.com/Ibsdlc8.png

does nothing

### LINKED ISSUE #6765: Infinite Bluespace Crystals
Step 1: Take a bluespace crystal or artificial bluespace crystal and drop it into an upgraded Ore Redemption Machine. This grants more bluespace mesh than the crystal is normally worth.

Step 2: Release bluespace mesh. This drops a Bluespace Polycrystal with however many crystals inside.

Step 3: Pull a crystal out of the polycrystal stack.

Step 4: Re-Deposit separated crystals into the ORM, which treats it as raw material for the purpose of bonus bluespace mesh. With Femto manipulators, this will give you two crystals worth of mesh per crystal put in.

You now have an infinite source of Bluespace Crystals. Repeat until your army of Bluespace Golems tear apart the spacetime continuum (or until this exploit is patched).

### LINKED ISSUE #6883: Close
ignore

### LINKED ISSUE #6910: Lavalands no longer adds plating to new tiles
Issue reported from  Round ID: 12997 (Citadel Station 13)

Reporting client version: 512

When placing down floor tiles on lavalands it should place down plating but now that is not the case. It only places down floor tiles. when removed it goes back to the default ash.

### LINKED ISSUE #6953: Window placement issues
All you need to know is for some reason directional windows can only be placed one per tile now rather than 4.

### LINKED ISSUE #7090: Morphine mood debuff staying
Issue reported from  Round ID: 13200 (Citadel Station 13)

Reporting client version: 512
Morphine addiction debuff does not go away after you are no longer addicted to morphine

[Reproduction]: # Get addicted to morphine, wait it out, and the debuff to your mood is still there

### LINKED ISSUE #7192: Light tiles can be made without using up the wired glass sheets
Issue reported from  Round ID: 13275 (Citadel Station 13)

Reporting client version: 512

[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # 
[Round ID]: # 

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: So basically i was making some light floor tiles and at the final step where you add metal sheets to the wired glass sheets, the wired glass sheets are not consumed, only the metal is consumed in this proccess.

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

### LINKED ISSUE #7269: Canvases Causing Dreamseeker Crashes
[Round ID]: 13394, and some far earlier rounds that I don't recall the ID of.

[Reproduction]: Currently using BYOND 512.1427, Windows 7.
I'm not sure how many people this is affecting, but it's almost certainly not an insignificant number, since during a round in which somebody sat in the bar painting, I noticed a disproportionate amount of people complaining about crashes (and then they stopped when that person went SSD and the painting was removed).
Anyway, the issue seems to occur whenever the game first tries to render a canvas that has been modified while out of your view. The problem doesn't occur when rendering a canvas that is in view when you log in, however.

Reproduction would almost certainly require two or more people, but the steps are pretty simple;
- Put a canvas down
- Start drawing on it
- Get somebody else to walk by
And as much of a dick move as it might be, it could also be tested by setting yourself up in an art storage and watching for people to go SSD as they walk by.

I wish I could offer more details, but that's about it.

### LINKED ISSUE #7418: Immortality Talisman Not despawning when sold to centcomm
So basically I don't know what causes it, if it's to do with the test merges or what but the immortality talisman which is worth 9835 credits can be sent on the cargo supply shuttle to centcomm and no matter what ya do, be it in any form of container or not, the immortality talisman will not disappear and you can send it back again and again for more credits as if ya sold a new one.

When in a container like a crate or bag the talisman will get sold and when the shuttle recalled the talisman is where the container used to be while the container itself is gone.

To reproduce the bug unless it was specific to the round which I cannot remember the ID of it is simple:

Acquire an Immortality Talisman
Put it in the supply shuttle like you would crates or anything else ya wanna sell or bounties.
send the shuttle away, you will receive the credits for it being sold, call the shuttle back like you normally would.
The Immortality Talisman will be right here you left it on the shuttle and can be sent again for more credits and this can be repeated.

### LINKED ISSUE #7537: TAIL WAGGING BUG!?
[Round ID]: #14325

[Testmerges]: # When being petted, your tail starts to wag, but if you climb on a table it'll stop.

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

### LINKED ISSUE #7539: Ingame Changelog hasn't been updated since April 2018
Reeeeeee

### LINKED ISSUE #7554: Cryo pods never places items into storage or log people cryoing on the console
[Round ID]: 
Any round that people cryo

[Reproduction]: 
Be any job and have any item that is listed to stay in round. Cryo, relise that your items are not in the console but openly on the ground for anyone to take, then hear 15 mins latter that people think your dead some were do to the console unable to display peoples name is they cryoed 

[For Admins]:
I quite remember a time when this worked, and items were recover via people with proper access like sec/heads/silicons

### LINKED ISSUE #7584: :thinking: AI core sprite results in invisible AI
[Round ID]: 14415
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # think the error comes from test merge #7540 (the meme merge)

[Reproduction]: the AI core sprite :thinking: doesn't exist when you select it, it just makes you invisible as the sprite's not there.

[For Admins]: # none I know of, seems to be just a simple bug or misnamed icon
thinking

### LINKED ISSUE #7588: A SECOND TAIL WAGGING BUG!?
[Round ID]: #14447
[Round ID]: # (**INCLUDE THE ROUND ID**)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # Someone pat me on the head while my tail was wagging, and my tail stopped wagging 
[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

### PR DESCRIPTION
**Pull request by Poojawa**
🆑 Poojawa
fix: buncha stuff from upstream
fix: Dogborg Tongue isn't always shocking.
fix: Boop module works again.
fix: Genitals are now transferred through cloning again.
fix: Cyropods now set their area controller more aggressively.
fix: Ash Drakes fully swallow prey again.
fix: Prey loop actually loops again. Silent belly mode should mute it.
fix: Help intent belly squirming now plays struggle messages again, any other intent starts escape timer.
tweak: His Grace requires 10 instead of 25 victims. Should promote !!FUN!! 
add: Air Alarms are visible in low light conditions
/:cl:

Hard sync of TG, Good to go now, after fighting with shitty map upkeep practices and Travis

Fixes Changlog. fixes a shitload of other stuff.

fixes #7588 
fixes #7584
fixes #7554
closes #7537 
fixes #7539
fixes #7418
fixes #7269
closes #7192
fixes #7090
closes #6953
closes #6910 (upstream issue)
closes #6883 
fixes #6765
fixes #6648
closes #6647
closes #6628 
fixes #6402
closes #6298 since it isn't an issue anymore honk
closes #6278 for same reason
closes #6255 because I know it works. honk.
closes #6043 because cryo can't reset religion.

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -200,5 +200,6 @@ tools/MapAtmosFixer/MapAtmosFixer/bin/*
 #GitHub Atom
 .atom-build.json
 
-#Jukebox audio files
-/config/jukebox_music/**/*
```
Comment (deathride58) [inline .gitignore]: needs to be readded

File: .dockerignore [hunk 2]
```diff
@@ -26,4 +25,6 @@ tgstation.lk
 tgstation.dyn.rsc
 libmariadb.dll
 rust_g.dll
+BSQL.dll
```
Comment (deathride58) [inline .dockerignore:28]: We haven't ported BSQL yet

File: dependencies.sh [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+#note, this also needs to be changed in the Dockerfile's initial FROM command
+#If someone has an idea for how to set that version within the Dockerfile itself without any other dependencies, feel free to PR it
+export BYOND_MAJOR=512
+export BYOND_MINOR=1441
+
+#rust_g git tag
+export RUST_G_VERSION=0.4.0
+
+#bsql git tag
+export BSQL_VERSION=v1.4.0.0
```
Comment (deathride58) [inline dependencies.sh]: We haven't ported BSQL yet

**Comment by Poojawa** [comment]
lol, only error was a permission denied

File: html/changelog.html [hunk 4]
```diff
@@ -23,26 +23,27 @@
...
+			<font size='3'><a href="https://discord.gg/3gJ9pnM"><b>...Or our Discord!</b></a></font>
 			</td>
 	</tr>
 </table>
 
 <table align='center' class="top">
 	<tr>
 		<td valign='top'>
-			<font size='2'><b>Current Project Maintainers:</b> <a href='https://github.com/tgstation?tab=members'>-Click Here-</a><br></font>
-			<font size='2'><b>Currently Active GitHub contributor list:</b> <a href='https://github.com/tgstation/-tg-station/graphs/contributors'>-Click Here-</a><br></font>
```
Comment (deathride58) [inline html/changelog.html:38]: Not really anything worth noting but I'm laughing pretty hard that TG's changelog has had outdated links for so long

File: html/changelog.html [hunk 5]
```diff
@@ -23,26 +23,27 @@
...
+			<font size='2'><b>Coders:</b> Poojawa, deathride58, kevinz000, Trilbyspaceclone, nik707, as well as the /tg/ crew. <br></font> 
+			<font size='2'><b>Spriters:</b> Michiyamenotehifunana, CameronWoof, and the folks who contributed to /tg/ station project. <br></font>
+			<font size='2'><b>Sounds:</b> /tg/ Sound crew.<br></font>
+			<font size='2'><b>Main Testers:</b> You poor saps, our player base. <br></font>
+			<font size='2'><b>Thanks to:</b> /tg/station, Baystation 12, /vg/station, NTstation, CDK Station devs, FacepunchStation, GoonStation devs, the original SpaceStation developers and Invisty for the title image.<br> Also a thanks to anybody who has contributed who is not listed here :( Ask to be added here on irc.</font>
+			<font size='2' color='red'><b><br>Have a bug to report?</b> Visit our <a href="https://github.com/Citadel-Station-13/Citadel-Station-13/issues">Issue Tracker</a>.<br></font>
+			<font size='2'>Please ensure that the bug has not already been reported upstream and <u><a href="https://github.com/tgstation/-tg-station/issues/724"><b>use the template provided here!</b></a></u>.</font>
```
Comment (deathride58) [inline html/changelog.html:46]: the `/-tg-station/` link is outdated, needs to be updated to `/tgstation/`

File: html/changelog.html [hunk 6]
```diff
@@ -55,1593 +56,1386 @@
...
-				<li class="bugfix">List Advanced Locator circuit now accepts refs as well as strings.</li>
-				<li class="bugfix">Fixed the Power Transmitter circuit not properly displaying a message when activated.</li>
-				<li class="bugfix">Medical Analyzer circuit can now properly scan non-human mobs.</li>
+			<h2 class="date">04 September 2018</h2>
+			<h3 class="author">Denton updated:</h3>
+			<ul class="changes bgimages16">
+				<li class="spellcheck">Mech construction messages no longer incorrectly mention high-tier stock parts.</li>
+				<li class="tweak">Added a nanite lab to Deltastation! It's at the old EXPERIMENTOR lab.</li>
+				<li class="tweak">Delta: Moved the Xenobiology disposals bin to be less obstructive. Added two sets of insulated gloves to Engineering.</li>
+				<li class="bugfix">Delta: Fixed scientists not having maintenance access near the circuitry lab and toxins launch chamber.</li>
```
Comment (deathride58) [inline html/changelog.html:65]: We don't have roundstart nanite labs here, changelog is false advertisement

**Review by deathride58 — CHANGES_REQUESTED** [review]
All of the RACT files in `tgui/src/` should probably be rolled back, since we don't have the mirror bot mirroring every single upstream change anymore, meaning upstream's tgui interfaces are likely incompatible.
Also BSQL hasn't been ported, so that doesn't have to be included

File: html/changelog.html (hunk 6 above)
Comment (Poojawa) [reply html/changelog.html:65]: considering there is a big sync that is "supposed" to be done, it's one of those things.

Comment (deathride58) [reply html/changelog.html:65]: A soft sync that only includes the backend stuff, yes.

Comment (Poojawa) [reply html/changelog.html:65]: unless nanite stuff's been mapped in to all maps, it might be worth considering doing a update for the little things like that.

the code base is hella out of date.

Comment (deathride58) [reply html/changelog.html:65]: Nanite stuff is available through RnD. It's something that's simply way too OP to be a roundstart thing. It's an example of some of the reasons why we're no longer a direct in-sync downstream of TG.
The only things that really should be in sync with upstream are backend stuff like BSQL, TGS, components, the admin system, the MC, atmos, etc etc. Bug fixes are also stuff that can, and should, be ported manually. It's alright if we're out of date in terms of ingame features/balance changes/etc.

File: tgui/src/interfaces/airlock_electronics.ract [hunk 7]
```diff
@@ -20,6 +20,12 @@
 			{{/each}}</tr>
 		</tbody>
 	</table>
+	<hr/>
+	<span class='highlight bold'>Unrestricted Access:</span>
```
Comment (Poojawa) [inline tgui/src/interfaces/airlock_electronics.ract:24]: https://github.com/tgstation/tgstation/pull/39147 This would be really good to port. @deathride58

File: tgui/src/interfaces/ore_redemption_machine.ract [hunk 8]
```diff
@@ -46,61 +46,70 @@
 		</ui-section>
 	{{/if}}
 </ui-display>
-<div class="display tabular">
```
Comment (Poojawa) [inline tgui/src/interfaces/ore_redemption_machine.ract:49]: https://github.com/tgstation/tgstation/pull/39118 this would also be something good to port.

File: tgui/src/interfaces/shuttle_manipulator/status.ract [hunk 9]
```diff
@@ -1,14 +1,33 @@
+<table width="100%">
 {{#each data.shuttles}}
-  <ui-section label='{{name}} ({{id}})'>
```
Comment (Poojawa) [inline tgui/src/interfaces/shuttle_manipulator/status.ract:2]: https://github.com/tgstation/tgstation/pull/39870 This would be nice to port also

**Comment by Poojawa** [comment]
This will require a pretty hefty database update, and must be done prior to this PR being merged. all of the resources are included. Maps were converted to the new decal based system.

**Comment by Poojawa** [comment]
excitedgargoyle angry sabre noises

**Comment by Poojawa** [comment]
>tools/travis/build_byond.sh: line 50: tools/deploy.sh: Permission denied

fuck if I know.

File: html/changelog.html (hunk 5 above)
Comment (Poojawa) [reply html/changelog.html:46]: these aren't outdated, actually. check 'em.

**Review by deathride58 — APPROVED** [review]
Expect a PR fixing stamina pretty soon after I hit the merge button, and expect a bunch of PRs axing TG's powercreep in the near, near future
